### PR TITLE
Typography +++

### PR DESCRIPTION
**Pull request by beejsbj**
- Using responsive techniques to have fluid font sizes
- standardizing the font sizes, weights, and other stuff into variables (this could be expanded on)
- adding some additional voices that i think could work
- Allowing em/strong to work outside of p/calm voice, sometimes you can add those to headings

### CODE REVIEW

**Comment by perpetual-education** [comment]
CleanShot 2023-10-01 at 08 07 13@2x

We need to be able to see what these things are at a glance

Even "Tune up typography styles" - or "Adjust type patterns" or "Assess global type rules" is 10x beetter.

And the tone of. "using... "  "adding...."  - is very passive and takes more work to understand.

What voice did you add? Why?

"Add microcopy voice to fill the need for form labels and figure captions" (this should also probably just be its own PR / and probably should be discussed even before a PR.  "Hey, guys - what about this idea" - etc...

Bigger projects might put this all in one PR / but this is a very small set of style rules --

**Review by sheriffderek — COMMENTED** [review]
As a user, if I was pulling this down into my code, I'd probably gut out the --steps / and I wouldn't want to use clamp for most things.

things like --font1  and --step-6  aren't very intuitive to me

things like --body-font - and --display-font  font are. 

The steps are great - but I think that should be on a project by project basis. We could leave notes on how to do it / and point them to the right resources or a video showing them how to do it --- but as a default / I think it's overcomplicated for most people. It could also be there - but a choice to opt-in to 'resizing' text vs static break-points. Is your project more like a poster? Or is it more like a newspaper? Because newspapers and magazines and books all of the same size type / and just the page changes --- vs a poster where everything gets bigger with bigger size (in some cases)

I think the motivation for this project is for us to use / but also to help people learn a little about CSS and not have the barrier so high and "unique" - where you have to learn the system to use it.

**Comment by beejsbj** [comment]
> things like --font1 and --step-6 aren't very intuitive to me
> 
> things like --body-font - and --display-font font are.

Hmm, i see your point, but i figured that these fonts would just be used to build out the text-voices anyway. (which would then be used across the site having more intuitive names). 
Same case for the steps, you'd wouldn't want to use them outside of building the text voices. (unless you need to use a more drastic shift at a breakpoint)

So, those variables don't really get used outside of the typography sheet. 


My understanding of pssst-css is for it to be like a baseline reset with some neat ideas for most standard websites (stuff like inner-column already push towards that idea), so I wasn't really thinking about other mediums like newspapers or posters.

I personally think the steps using clamps in that way is a generally a better design pattern than using breakpoints especially for most standard sites. (plus people get to see the power of clamp :D)

**Comment by sheriffderek** [comment]
Let's revisit this in person - with examples.

**Pull request closed without merging**
