### PR TITLE
Adding a reset and setup for Buttons

### PR DESCRIPTION
**Pull request by beejsbj**
Self explanatory,
Button resets were missing from the reset. would be useful to have them.

(other input types might need this too)

### CODE REVIEW

**Comment by perpetual-education** [comment]
> Self explanatory,

Is it ?  I think that it's worth the time to outline exactly what is happening and why (on a project that is this specific). On a not-css-centric project.. . explaining why you added or removed a margin would be very annoying.

**Comment by perpetual-education** [comment]
OK Formatting. We need to make an official plan for this: 

CleanShot 2023-10-01 at 08 02 13@2x

If you entire commit shows as "Everything changed" - it's a lot of work for the person who has to check it over. Who knows what happened here....

CleanShot 2023-10-01 at 08 05 03@2x

It's getting better at being able to show a layer deeper of what changed on top of bigger changes...

But this commit - is not going to fly. However, it does bring up the need for a decision on code style.

**Comment by perpetual-education** [comment]
Also - what's this: 

CleanShot 2023-10-01 at 08 04 30@2x

**Comment by beejsbj** [comment]
> OK Formatting. We need to make an official plan for this:
> 
> CleanShot 2023-10-01 at 08 02 13@2x
> If you entire commit shows as "Everything changed" - it's a lot of work for the person who has to check it over. Who knows what happened here....
> 
> CleanShot 2023-10-01 at 08 05 03@2x
> It's getting better at being able to show a layer deeper of what changed on top of bigger changes...
> 
> But this commit - is not going to fly. However, it does bring up the need for a decision on code style.

Prettier seems the way to go, considering how widely used it is.

**Comment by beejsbj** [comment]
> Also - what's this:
> 
> CleanShot 2023-10-01 at 08 04 30@2x

My fork's main branch was in a lot of conflict, so i overwrote my main with PE's repo.

**Comment by perpetual-education** [comment]
> OK Formatting. We need to make an official plan for this:

Even if we use Prettier - we still have to make a plan and choose widths and things -

**Pull request closed without merging**
